- name: ğŸ“‚ Chercher la derniÃ¨re config de backup pour {{ inventory_hostname }}
  find:
    path: "{{ playbook_dir }}/../backups/{{ inventory_hostname }}"
    patterns: "config-*.conf"
    age_stamp: mtime
  register: saved_configs

- name: ğŸ•˜ Prendre la plus rÃ©cente
  set_fact:
    last_backup: "{{ (saved_configs.files | sort(attribute='mtime'))[-1].path }}"

- name: â™»ï¸ Restaurer la derniÃ¨re configuration sauvegardÃ©e
  eos_config:
    src: "{{ last_backup }}"
    replace: config
